/**
 * Identifiers.
 *
 * Manak's ids are ULIDs: 26 characters of Crockford base32, the first ten
 * encoding a 48-bit millisecond timestamp and the last sixteen encoding 80 random
 * bits. Three properties earn them over an auto-incrementing integer or a UUIDv4.
 *
 * They sort by creation time as text, which means `order by id` is a stable
 * tiebreak everywhere and the export in `docs/` diffs in a sensible order.
 *
 * They carry no information about how many of a thing exist. A sequential integer
 * in a URL tells a participant how many teams registered before them, and tells
 * anyone who can read one id that id minus one probably exists too.
 *
 * They are generated by the application, not the database, so an insert knows the
 * id it is about to write and the ledger entry describing that insert can name its
 * subject inside the same transaction.
 *
 * Crockford base32 excludes I, L, O and U, so an id read aloud or copied out of a
 * screenshot has no ambiguous characters and cannot spell anything.
 */

import { randomFillSync } from "node:crypto";

/**
 * The alphabet, exported because the API layer publishes a JSON Schema pattern for
 * ids and a pattern that disagreed with `isId` would be a document that lies.
 */
export const ID_ALPHABET = "0123456789ABCDEFGHJKMNPQRSTVWXYZ";
const ALPHABET = ID_ALPHABET;
const TIME_CHARS = 10;
const RANDOM_BYTES = 10;
const RANDOM_CHARS = 16;
export const ID_LENGTH = TIME_CHARS + RANDOM_CHARS;

/** The largest instant a 48-bit timestamp can hold: 10889-08-02. */
export const MAX_ID_TIME = 2 ** 48 - 1;

/** A source of random bytes. Injected so a test can make ids reproducible. */
export type Random = (into: Uint8Array) => void;

export const systemRandom: Random = (into) => {
  randomFillSync(into);
};

/**
 * A generator of ids that are unique and monotonic within one process.
 *
 * Monotonicity is not free: two ids created in the same millisecond would
 * otherwise sort arbitrarily, and a seeded event that inserts sixty projects in
 * one tick would produce a ranking whose tiebreak order changes between runs.
 * When the clock has not advanced, the random field is incremented instead of
 * redrawn — the ULID specification's own answer, and it keeps the sort total.
 */
export function makeIds(
  now: () => number,
  random: Random = systemRandom,
): () => string {
  let lastTime = -1;
  const last = new Uint8Array(RANDOM_BYTES);
  return () => {
    const at = Math.floor(now());
    if (!Number.isFinite(at) || at < 0 || at > MAX_ID_TIME) {
      throw new RangeError(`clock outside the representable range: ${at}`);
    }
    if (at > lastTime) {
      lastTime = at;
      random(last);
    } else {
      // Same millisecond, or a clock that went backwards. Either way, stay on
      // the last timestamp and step the random field so the id still increases.
      increment(last);
    }
    return encodeTime(lastTime) + encodeRandom(last);
  };
}

/** Add one to a big-endian byte string, in place. */
function increment(bytes: Uint8Array): void {
  for (let i = bytes.length - 1; i >= 0; i--) {
    const next = ((bytes[i] as number) + 1) & 0xff;
    bytes[i] = next;
    if (next !== 0) return;
  }
  // 2^80 ids inside one millisecond. Unreachable, and a silent wrap here would
  // hand out a duplicate id, so it is an error rather than a comment.
  throw new RangeError("id randomness exhausted within a single millisecond");
}

function encodeTime(at: number): string {
  let out = "";
  let rest = at;
  for (let i = 0; i < TIME_CHARS; i++) {
    out = (ALPHABET[rest % 32] as string) + out;
    rest = Math.floor(rest / 32);
  }
  return out;
}

/** 80 bits as 16 characters: five bytes to eight characters, twice. */
function encodeRandom(bytes: Uint8Array): string {
  let out = "";
  for (let offset = 0; offset < RANDOM_BYTES; offset += 5) {
    let chunk = 0;
    for (let i = 0; i < 5; i++) chunk = chunk * 256 + (bytes[offset + i] as number);
    let group = "";
    for (let i = 0; i < 8; i++) {
      group = (ALPHABET[chunk % 32] as string) + group;
      chunk = Math.floor(chunk / 32);
    }
    out += group;
  }
  return out;
}

/** True for a well-formed id. Used to reject a path parameter before a query. */
export function isId(text: string): boolean {
  if (text.length !== ID_LENGTH) return false;
  for (const character of text) if (!ALPHABET.includes(character)) return false;
  return true;
}

/**
 * The instant an id was minted, in epoch milliseconds.
 *
 * Useful in diagnostics and in tests that assert ordering. Not a substitute for a
 * `created_at` column: the timestamp inside an id is when the process generated
 * it, which is not necessarily when the row was committed.
 */
export function idTime(id: string): number {
  if (!isId(id)) throw new RangeError(`not an id: ${JSON.stringify(id)}`);
  let at = 0;
  for (let i = 0; i < TIME_CHARS; i++) at = at * 32 + ALPHABET.indexOf(id[i] as string);
  return at;
}
