/** Reproducible fixture proof, separate from simulations with known ground truth. */
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { openDatabase, migrate, makeContext, manualClock, loadJudgingInput } from "../src/db/index.ts";
import { normalizeScores } from "../src/judging/normalize.ts";
import { judgingReadiness } from "../src/judging/readiness.ts";
import { seedFixtures } from "./seed-fixtures.ts";

const fixtureBytes = readFileSync(new URL("./fixtures.json", import.meta.url));
const fixture = JSON.parse(fixtureBytes.toString("utf8"));
const at = Date.parse("2026-09-26T12:00:00Z");
const db = openDatabase(":memory:");
try {
  migrate(db);
  const { event } = db.tx(() => seedFixtures(makeContext(db, { clock: manualClock(at) }), at));
  const input = loadJudgingInput(db, event.id);
  if (input.ballots.length !== fixture.scores.length) throw new Error("Fixture ballots were dropped or merged during import.");
  const projects = db.all<{ id: string; title: string; submitted_at: number }>(
    "select id, title, submitted_at from project where event_id = :event order by id", { event: event.id });
  if (projects.length !== fixture.projects.length) throw new Error("Fixture projects were dropped during import.");
  for (const project of projects) {
    const source = fixture.projects.find((p: { id: string }) => p.id === project.id);
    if (project.submitted_at !== Date.parse(source.submitted_at)) throw new Error("Submission timestamp drift.");
  }
  const fit = normalizeScores(input.rubric, input.ballots);
  const readiness = judgingReadiness({ projects: projects.map((p) => p.id), ballots: input.ballots,
    reviewsPerProject: event.reviews_per_project, rubric: fit, pairwise: null, pairwiseEnabled: false });
  const titles = new Map(projects.map((p) => [p.id, p.title.replaceAll("|", "\\|")]));
  const lines = ["# Fixture normalization proof", "",
    "Generated by `npm run prove:fixtures`; verify with `npm run prove:fixtures -- --check`.", "",
    `Fixture SHA-256: \`${createHash("sha256").update(fixtureBytes).digest("hex")}\`.`, "",
    "This identifies the bundled fixture bytes. Remote provenance has not been verified; replace with the official file if its checksum differs.", "",
    `${projects.length} projects, ${fixture.judges.length} registered judges, ${input.ballots.length} imported ballots. No project or score is silently dropped. Original submission timestamps are preserved.`, "",
    `Method: ${fit.method}. Converged: ${fit.converged}. Scale settled: ${fit.settled}.`, "",
    "The import uses equal weights on functionality, quality and innovation, each scored 1–5. These weights are an explicit importer choice, not a claimed organizer requirement. See JUDGING.md for the fitted additive effects, scale shrinkage, regularization and disconnected-panel limitations.", "",
    "Fixtures have no known true ordering. Rank movement demonstrates the adjustment; it does not prove a better ranking. The separate normalization simulation measures recovery against planted truth and includes unfavorable cases.", "",
    "| Project | Reviews | Raw mean | Adjusted | Raw rank | Adjusted rank | Movement |", "|---|---:|---:|---:|---:|---:|---:|",
    ...fit.projects.slice().sort((a, b) => a.rankAdjusted - b.rankAdjusted).map((p) =>
      `| ${titles.get(p.project)} | ${p.ballots} | ${p.rawMean.toFixed(4)} | ${p.adjusted.toFixed(4)} | ${p.rankRaw} | ${p.rankAdjusted} | ${p.rankMove} |`), "",
    "## Evidence checks", "", ...readiness.checks.map((c) => `- **${c.status}: ${c.title}.** ${c.detail}`), "",
    "## Scoring range", "", ...fit.judges.filter((j) => j.discrimination !== "ok").map((j) => `- ${j.judge}: ${j.discrimination}. Retained with regularized scale; not silently excluded.`), "",
    "## Model warnings", "", ...fit.warnings.map((w) => `- ${w}`), ""];
  const output = lines.join("\n");
  const path = new URL("../docs/proof/fixtures.md", import.meta.url);
  if (process.argv.includes("--check")) {
    if (readFileSync(path, "utf8") !== output) throw new Error("Fixture proof is stale. Run npm run prove:fixtures.");
  } else writeFileSync(path, output);
  process.stdout.write(`Fixture proof: ${projects.length} projects and ${input.ballots.length} ballots verified.\n`);
} finally { db.close(); }
