/** Bounded convergence experiment on the bundled fixture and planted-truth regimes. */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { openDatabase, migrate, makeContext, manualClock, loadJudgingInput } from "../src/db/index.ts";
import { normalizeScores } from "../src/judging/normalize.ts";
import { simulateEvent } from "../src/judging/simulate.ts";
import { kendallTau } from "../src/judging/stats.ts";
import { weightedTotal } from "../src/judging/weighted.ts";
import type { Ballot, Rubric } from "../src/judging/types.ts";
import { seedFixtures } from "./seed-fixtures.ts";

const out = fileURLToPath(new URL("../docs/proof/convergence.md", import.meta.url));
const schedules = [
  { rounds: 3, backfitIterations: 200 },
  { rounds: 6, backfitIterations: 400 },
  { rounds: 12, backfitIterations: 800 },
  { rounds: 12, backfitIterations: 1000 },
  { rounds: 20, backfitIterations: 1000 },
];
type Event = { rubric: Rubric; ballots: Ballot[]; truth?: Map<string, number> };

function split(ballots: Ballot[]): { train: Ballot[]; held: Ballot[] } {
  const counts = new Map<string, number>();
  for (const b of ballots) counts.set(b.project, (counts.get(b.project) ?? 0) + 1);
  const train: Ballot[] = [];
  const held: Ballot[] = [];
  for (const [i, b] of ballots.entries()) {
    if (i % 5 === 0 && (counts.get(b.project) ?? 0) > 1) {
      held.push(b); counts.set(b.project, (counts.get(b.project) ?? 0) - 1);
    } else train.push(b);
  }
  return { train, held };
}

function row(label: string, event: Event, opt: typeof schedules[number]): string {
  const { train, held } = split(event.ballots);
  const start = performance.now();
  const fit = normalizeScores(event.rubric, event.ballots, opt);
  const elapsed = performance.now() - start;
  const heldoutFit = normalizeScores(event.rubric, train, opt);
  const project = new Map(heldoutFit.projects.map((p) => [p.project, p.adjusted]));
  const judge = new Map(heldoutFit.judges.map((j) => [j.judge, j]));
  const residuals = held.flatMap((b) => {
    const adjusted = project.get(b.project);
    const effect = judge.get(b.judge);
    if (adjusted === undefined || effect === undefined) return [];
    const predicted = heldoutFit.grandMean + effect.leniency + effect.scale * (adjusted - heldoutFit.grandMean);
    return [weightedTotal(event.rubric, b.scores) - predicted];
  });
  const rmse = residuals.length ? Math.sqrt(residuals.reduce((a, x) => a + x * x, 0) / residuals.length) : NaN;
  const common = event.truth ? fit.projects.filter((p) => event.truth!.has(p.project)) : [];
  const tau = event.truth && common.length > 1
    ? kendallTau(common.map((p) => event.truth!.get(p.project)!), common.map((p) => p.adjusted)) : NaN;
  return `| ${label} | ${opt.rounds}/${opt.backfitIterations} | ${fit.converged} | ${fit.settled} | ${fit.outerMovement.toExponential(2)} | ${fit.leniencyResidual.toExponential(2)} | ${fit.sweeps} | ${elapsed.toFixed(1)} | ${rmse.toFixed(3)} | ${Number.isNaN(tau) ? "—" : tau.toFixed(3)} |`;
}

const db = openDatabase(":memory:");
try {
  migrate(db);
  const at = Date.parse("2026-09-27T12:00:00Z");
  const { event } = db.tx(() => seedFixtures(makeContext(db, { clock: manualClock(at) }), at));
  const fixture = loadJudgingInput(db, event.id);
  const regimes: [string, Event][] = [["fixture", { rubric: fixture.rubric, ballots: fixture.ballots }]];
  const plans = [
    ["balanced", { imbalance: 0, reviewsPerProject: 4 }],
    ["sparse", { imbalance: 0.65, reviewsPerProject: 2 }],
    ["disconnected", { imbalance: 1, reviewsPerProject: 3 }],
    ["adversarial", { imbalance: 0.7, reviewsPerProject: 4, strategicJudges: 2 }],
  ] as const;
  for (const [name, settings] of plans) {
    for (let seed = 0; seed < 5; seed++) {
      const simulated = simulateEvent({ projects: 40, judges: 10, leniencySd: 0.6,
        scaleSpread: 0.4, noise: 0.35, ...settings, seed: `${name}-${seed}` });
      regimes.push([`${name} ${seed + 1}`, simulated]);
    }
  }
  const lines = ["# Convergence budget experiment", "",
    "Generated by `npm run prove:convergence`. Five fixed seeds per synthetic regime. Convergence columns fit every ballot; a separate deterministic fifth is held out when project coverage permits. Held-out RMSE predicts the original weighted score using the training fit's project and judge effects. Tau compares full-fit project order with planted truth; the real fixture has no known truth. Times are machine dependent.", "",
    "| Regime | Rounds/inner cap | Inner converged | Scale settled | Last outer move | Pending leniency | Sweeps | ms | Held-out RMSE | Truth tau |",
    "|---|---:|---|---|---:|---:|---:|---:|---:|---:|",
    ...regimes.flatMap(([name, data]) => schedules.map((opt) => row(name, data, opt))), "",
    "The selected default is 12 outer rounds and 1,000 inner sweeps, with a 0.01 outer movement tolerance. On the full fixture it reaches both numerical checks in about 10,636 sweeps; the 3/200 schedule reaches neither. The fixture held-out score prediction is slightly worse (1.038 versus 1.017 RMSE), so convergence is presented as internal numerical consistency, not improved predictive accuracy. Planted-truth tau and held-out error across the other regimes remain visible above.", "",
    "Numerical convergence and sampling adequacy are separate. Sparse and disconnected panels need independent reviews even when the optimizer stops. Settings are chosen across prediction, truth recovery, and bounded work, never for a preferred fixture winner.", ""];
  if (process.argv.includes("--check")) {
    // Runtime varies by host, so only compare the stable columns.
    const stable = (s: string) => s.replace(/\| \d+\.\d \|/g, "| <runtime> |");
    if (stable(readFileSync(out, "utf8")) !== stable(lines.join("\n"))) throw new Error("Convergence proof is stale.");
  } else writeFileSync(out, lines.join("\n"));
  process.stdout.write("Convergence schedules tested across fixture and four synthetic regimes.\n");
} finally { db.close(); }
